name: Ubuntu RDP  root 123456 >>>@zhuzhuwei666

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 9999

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install xrdp and configure for root
        run: |
          # Install xrdp
          sudo apt-get update
          sudo apt-get install -y xrdp

          # Configure xrdp to use the root user
          sudo sed -i 's/allowed_users=console/allowed_users=anybody/' /etc/X11/Xwrapper.config

          # Set up the password for the root user to "admin"
          echo 'root:123456' | sudo chpasswd

      - name: Install ngrok
        run: |
          # Download ngrok
          sudo wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz 
          sudo tar -xvzf ngrok-v3-stable-linux-amd64.tgz
          sudo mv ngrok /usr/local/bin/ 

      - name: Start ngrok TCP tunnel
        run: |
          # Retrieve the ngrok authtoken from GitHub secrets
          NGROK_AUTH_TOKEN=${{ secrets.NGROK_AUTH_TOKEN }}

          # Authenticate ngrok using the authtoken
          sudo ngrok authtoken $NGROK_AUTH_TOKEN

          # Start ngrok with port 3389 (RDP)
          sudo ngrok tcp 3389

          # Sleep for a few seconds to ensure ngrok is running
          sleep 5

          # Get the public IP address provided by ngrok
          echo "::set-output name=url::$(curl -s localhost:4040/api/tunnels | jq -r .tunnels[0].public_url)"
           
          # Output the public  IP address&login imformation
          echo "Public IP Address: $public_ip"
          echo "username:root"
          echo "password:123456"

      - name: Keep Alive
        run: |
          # Add a long-running command to keep the workflow alive
          while true; do
            echo "Workflow is running..."
            sleep 5184000  # Sleep for 1 hour
          done
