name: Ubuntu SSH  root 123456 >>>@zhuzhuwei666

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 9999

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: System Update and configure for root
        run: |
          # System Update
          sudo apt-get update

          # Install nohup
          sudo apt-get install coreutils

          # Set up the password for the root user to "admin"
          echo 'root:123456' | sudo chpasswd

      - name: Install ngrok
        run: |
          # Download ngrok
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
          tar -xvzf ngrok-v3-stable-linux-amd64.tgz
          chmod +xrw ngrok
          mv ngrok /usr/local/bin/

      - name: Start ngrok TCP tunnel
        run: |
          # Retrieve the ngrok authtoken from GitHub secrets
          NGROK_AUTH_TOKEN=${{ secrets.NGROK_AUTH_TOKEN }}

          # Authenticate ngrok using the authtoken
          ngrok authtoken $NGROK_AUTH_TOKEN

          # Start ngrok with port 3389 (RDP)
          nohup ngrok tcp 22

          # Sleep for a few seconds to ensure ngrok is running
          sleep 5

      - name: Connect Ngrok.
        run: |
          # Get the public IP address provided by ngrok
          public_ip=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
           
          # Output the public IP address and login imformation
          echo "Public IP Address: $public_ip"
          echo "username:root"
          echo "password:123456"

      - name: Keep Alive
        run: |
          # Add a long-running command to keep the workflow alive
          while true; do
            echo "Workflow is running..."
            sleep 5184000  # Sleep for 1 hour
          done
